services:
  mysql:
    image: mysql:8 # 使用的镜像
    container_name: parrot-oj-mysql # 启动的实例名称
    environment:
      MYSQL_ROOT_PASSWORD: 1234 # root 用户密码
    ports:
      - "3306:3306" # 端口映射
    volumes:
      - ./.mysql-data:/var/lib/mysql # 将数据目录挂载到本地目录以进行持久化
      - ./mysql-init:/docker-entrypoint-initdb.d # 启动脚本
    restart: always # 崩溃后自动重启
#    network_mode: host
    networks:
      - my_network # 指定网络
  redis:
    image: bitnami/redis:7.4.1
    container_name: parrot-oj-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - my_network
#    network_mode: host
    volumes:
      - ./.redis-data:/data # 持久化
  rabbitmq:
    image: rabbitmq:3.12.13-management # 支持管理面板的消息队列
    container_name: parrot-oj-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ Dashboard 端口
    volumes:
      - ./.rabbitmq-data:/var/lib/rabbitmq # 持久化
    networks:
      - my_network
#    network_mode: host

  nacos:
    image: nacos/nacos-server:v2.2.0
    container_name: parrot-oj-nacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    networks:
      - my_network
#    network_mode: host
    environment:
      - MODE=standalone # 单节点模式启动
      - TZ=Asia/Shanghai # 控制时区

  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: parrot-oj-elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=1234
      - TZ=Asia/Shanghai
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true

    volumes:
      # - ./config:/usr/share/elasticsearch/config
#      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/data:/usr/share/elasticsearch/data
      - ./es/plugins:/usr/share/elasticsearch/plugins
    networks:
      - my_network
#    network_mode: host


  kibana:
    container_name: parrot-oj-kibana
    image: kibana:7.17.0
    restart: always
    ports:
      - "5601:5601"
#    volumes:
#      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - my_network
#    network_mode: host
    depends_on:
      - elasticsearch
  Etcd:
    image: 'bitnami/etcd:latest'
    container_name: parrot-oj-etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://Etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - my_network
#    network_mode: host



  sentinel:
    image: herodotus/sentinel-dashboard:1.8.6
    container_name: parrot-oj-sentinel-dashboard
    environment:
      SENTINEL_ADMIN_USERNAME: admin
      SENTINEL_ADMIN_PASSWORD: 1234
    ports:
      - "8858:8858"
    networks:
      - my_network
#    network_mode: host



networks:
  my_network:


